### ISSUE TITLE
Run HelloWorld In Main Class

### ISSUE THREAD

**Issue by fansonfong** [vladsoroka/GradleJniSample#2]
Hello, I have successfully run this project with `./gradlew test`.  
Then when I try to run `new HelloWorld().print()` in java main class using IntelliJ's Run button, it failed with the following message:

```
Execution failed for task ':Script.main()'.
> Process 'command '/Users/frank/Library/Java/JavaVirtualMachines/adopt-openjdk-11.0.8/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

Here is my Script.java file definition in the same folder of HelloWorld.java:

```
public class Script {
    public static void main(String[] args) {
        new HelloWorld().print();
    }
}

```
Do you know how do fix it? Thanks for your reply!

**Comment by poorvajappja** [comment]
Same issue give a solution.

**Comment by harideva16** [comment]
**Same error**


    10:30:26: Executing task 'HelloWorld.main()'...

    > Task :compileJava
    > Task :processResources NO-SOURCE
    > Task :classes

    > Task :HelloWorld.main() FAILED
    2 actionable tasks: 2 executed
    java.lang.UnsatisfiedLinkError: no hello in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at HelloWorld.<clinit>(HelloWorld.java:5)
    Exception in thread "main" 
    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':HelloWorld.main()'.
    > Process 'command 'C:/Program Files/OpenJDK/openjdk-8u292-b10/bin/java.exe'' finished with non-zero exit value 1

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to 
    get full insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 5s
     10:30:33: Task execution finished 'HelloWorld.main()'.

**Comment by liushuai42** [comment]
The root cause is that the JVM doesn't know where to find the native library, so we can use `java.library.path` to achieve this.

**Method 1**: using `application` plugin and so we can config the flag by gradle config and run the application by `./gradlew run`
```diff
diff --git a/build.gradle b/build.gradle
index 4d4257e..fa934d5 100644
--- a/build.gradle
+++ b/build.gradle
@@ -1,5 +1,6 @@
 plugins {
     id 'java'
+    id 'application'
 }

 group 'org.example'
@@ -15,6 +16,10 @@ dependencies {
     testCompile group: 'junit', name: 'junit', version: '4.12'
 }

+application {
+    mainClassName = 'HelloWorld'
+    applicationDefaultJvmArgs = ["-Djava.library.path=${file("${project(":hello").buildDir}/lib/main/debug").absolutePath}"]
+}
+
+run.dependsOn ':hello:linkDebug'

 test {
     systemProperty "java.library.path", file("${project(":hello").buildDir}/lib/main/debug").absolutePath
```
```diff
diff --git a/src/main/java/HelloWorld.java b/src/main/java/HelloWorld.java
index e9702f3..b650bf8 100644
--- a/src/main/java/HelloWorld.java
+++ b/src/main/java/HelloWorld.java
@@ -4,4 +4,8 @@ public class HelloWorld {
     static {
         System.loadLibrary("hello");
     }
+
+    public static void main(String[] args) {
+        new HelloWorld().print();
+    }
 }
\ No newline at end of file
```

**Method 2**:  Using IDEA run configration
To use the run button, you should edit the 'Run/Debug configrations' and 'Add VM options'

![Image](https://github.com/user-attachments/assets/5b9270cf-e615-4d88-b72c-edac06e4d0c3)

![Image](https://github.com/user-attachments/assets/3245e915-be27-477a-8a64-d9e061eb8a04)
You can use absolute path or relative path relative to 'Working directory' which should be the directory which the native library located in.
